#!/usr/bin/env python3
"""Convert a PNG into main/logo_bitmap.h for the AtomS3 boot screen.

The output is a 1-bit, MSB-first bitmap meant to be drawn with M5GFX
`drawBitmap` (NOT `drawXBitmap`, which is LSB-first). Foreground (logo ink)
is encoded as 1 bits and rendered in the color passed to drawBitmap.

Usage:
    python3 tools/png_to_logo.py LOGO.png [--width 120] [--threshold 140]
                                          [--out main/logo_bitmap.h] [--invert]

Notes:
- Source art should be dark ink on a light background. Use --invert for
  light ink on dark.
- Width is the panel target (AtomS3 is 128 px wide); height scales to keep
  the aspect ratio. Whitespace margins are auto-trimmed first.
"""
import argparse
import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow required: pip install Pillow")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("png", help="source PNG path")
    ap.add_argument("--width", type=int, default=120, help="target width in px")
    ap.add_argument("--threshold", type=int, default=140,
                    help="0-255; pixels darker than this become foreground")
    ap.add_argument("--out", default="main/logo_bitmap.h", help="output header")
    ap.add_argument("--invert", action="store_true",
                    help="treat light pixels as foreground")
    args = ap.parse_args()

    img = Image.open(args.png).convert("L")
    if args.invert:
        img = img.point(lambda v: 255 - v)

    # Trim background margins (background assumed light).
    mask = img.point(lambda v: 0 if v < args.threshold else 255)
    bbox = mask.getbbox()
    if bbox:
        img = img.crop(bbox)

    target_w = args.width
    target_h = max(1, round(img.height * target_w / img.width))
    img = img.resize((target_w, target_h), Image.LANCZOS)

    stride = (target_w + 7) // 8
    data = bytearray(stride * target_h)
    px = img.load()
    for y in range(target_h):
        for x in range(target_w):
            if px[x, y] < args.threshold:  # dark = foreground
                data[y * stride + (x // 8)] |= (0x80 >> (x % 8))

    lines = [
        "#pragma once",
        "#include <stdint.h>",
        "",
        "/* baargsiitsch boot logo — auto-generated by tools/png_to_logo.py",
        f" * Bitmap: {target_w}x{target_h} px, MSB-first (draw with drawBitmap,",
        " * NOT drawXBitmap), 1=foreground.",
        f" * Source: {os.path.basename(args.png)}",
        " */",
        f"#define LOGO_W      {target_w}",
        f"#define LOGO_H      {target_h}",
        "",
        "static const uint8_t logo_bitmap[] = {",
    ]
    for y in range(target_h):
        row = data[y * stride:(y + 1) * stride]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in row) + ",")
    lines.append("};")

    with open(args.out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {args.out}: {target_w}x{target_h}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
